version: '3'

services:
  keycloak:
    build: .
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./keycloak/themes/:/opt/keycloak/themes
      - ./keycloak/startup-scripts/disable-theme-cache.cli:/opt/keycloak/startup-scripts/disable-theme-cache.cli
    networks:
      - keycloak_network
  postgres:
    image: postgres
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  postgres_data:
      driver: local
